trigger:
  branches:
    include:
        - main

pool:
 name:
   Practice

steps:
- task: TerraformInstaller@1
  displayName: 'installing Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent'
    commandOptions: '-migrate-state'
    backendServiceArm: 'pipeline-creation'
    backendAzureRmOverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'
    backendAzureRmResourceGroupName: 'DoNotDeleteRg'
    backendAzureRmStorageAccountName: 'donotdeletestorage555'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'akstfstate'
- task: TerraformTask@5
  displayName: 'validating aks codes'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent'
- task: TerraformTask@5
  displayName: 'planning stage to review'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent'
    environmentServiceNameAzureRM: 'pipeline-creation'
    environmentAzureRmOverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'

- task: TerraformTask@5
  displayName: 'applying for aks cluster'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'pipeline-creation'
    environmentAzureRmOverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'




